services:
  mail-observer:
    build: .
    container_name: mail-observer
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Berlin
    command: python -m app.main

  mail-web:
    build: .
    container_name: mail-web
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Irkutsk
    ports:
      - "8080:8080"
    command: gunicorn -b 0.0.0.0:8080 app.web:app